import type { Category } from '../types/category';
import type { HomepageBanner, HomepagePromoCard } from '../types/homepage';
import type { Product } from '../types/product';
import deltaSeriesUrl from '../assets/categories/delta-series.png';
import ocean2Url from '../assets/categories/ocean-2.png';
import powerBanksUrl from '../assets/categories/power-banks.png';
import refurbishedUrl from '../assets/categories/refurbished.png';
import riverSeriesUrl from '../assets/categories/river-series.png';
import smartDevicesUrl from '../assets/categories/smart-devices.png';
import solarPanelsUrl from '../assets/categories/solar-panels.png';
import streamSeriesUrl from '../assets/categories/stream-series.png';
import streamSolarSystemUrl from '../assets/categories/stream-solar-system.png';
import showcaseBannerUrl from '../assets/heroes/hero-delta-max.png';
import solarHomeUrl from '../assets/heroes/hero-solar-home.png';

export const demoCategories: Category[] = [
  { id: 'power-stations', name: 'Power Stations', slug: 'power-stations', description: 'Portable power stations for home backup, outdoor use, and business continuity.', image_url: deltaSeriesUrl, is_new: false, active: true },
  { id: 'stream-series', name: 'STREAM Series Plug & Play Solar Plant', slug: 'stream-series', description: 'Plug-and-play balcony solar solutions for simple home energy production.', image_url: streamSeriesUrl, is_new: true, active: true },
  { id: 'stream-solar-system', name: 'STREAM Plug & Play Solar System', slug: 'stream-solar-system', description: 'Compact solar systems designed for everyday home energy savings.', image_url: streamSolarSystemUrl, is_new: true, active: true },
  { id: 'delta-series', name: 'DELTA Series', slug: 'delta-series', description: 'High-capacity portable stations for home backup and professional power.', image_url: deltaSeriesUrl, is_new: false, active: true },
  { id: 'river-series', name: 'RIVER Series', slug: 'river-series', description: 'Light portable power for outdoor use, travel, and everyday essentials.', image_url: riverSeriesUrl, is_new: true, active: true },
  { id: 'solar-panels', name: 'Solar Panels', slug: 'solar-panels', description: 'Foldable and fixed solar panels for clean charging anywhere.', image_url: solarPanelsUrl, is_new: true, active: true },
  { id: 'solar-generators', name: 'Solar Generators', slug: 'solar-generators', description: 'Solar generator kits combining clean charging with dependable backup power.', image_url: streamSolarSystemUrl, is_new: false, active: true },
  { id: 'smart-devices', name: 'Smart Devices', slug: 'smart-devices', description: 'Connected devices for monitoring and optimizing home energy use.', image_url: smartDevicesUrl, is_new: true, active: true },
  { id: 'accessories', name: 'Accessories', slug: 'accessories', description: 'Charging cables, adapters, batteries, and add-ons for Eco Buka systems.', image_url: powerBanksUrl, is_new: false, active: true },
  { id: 'solutions', name: 'Solutions', slug: 'solutions', description: 'Complete energy solutions for homes, businesses, travel, and backup needs.', image_url: showcaseBannerUrl, is_new: false, active: true },
  { id: 'ocean-2', name: 'OCEAN 2', slug: 'ocean-2', description: 'Dedicated energy equipment for pool, outdoor, and seasonal systems.', image_url: ocean2Url, is_new: false, active: true },
  { id: 'power-banks', name: 'Power Banks', slug: 'power-banks', description: 'Compact mobile charging for daily carry and travel backup.', image_url: powerBanksUrl, is_new: true, active: true },
  { id: 'refurbished', name: 'Refurbished', slug: 'refurbished', description: 'Professionally inspected value products for budget-friendly energy access.', image_url: refurbishedUrl, is_new: false, active: true },
];

export const demoProducts: Product[] = [
  {
    id: 'eb-500',
    name: 'Eco Buka Station 500',
    slug: 'eco-buka-station-500',
    category_id: 'power-stations',
    category: 'Power Stations',
    short_description: 'Everyday portable power for phones, laptops, cameras, routers, and small appliances.',
    description: 'A compact, presentation-ready power station for home backup and outdoor use.',
    price: 499,
    old_price: 579,
    image_url: deltaSeriesUrl,
    specs: { Capacity: '512Wh', Output: '500W', 'Solar Input': '220W', Weight: '6.4kg' },
    badge: 'Best Seller',
    featured: true,
    active: true,
  },
  {
    id: 'eb-1200',
    name: 'Eco Buka Station 1200',
    slug: 'eco-buka-station-1200',
    category_id: 'power-stations',
    category: 'Power Stations',
    short_description: 'More capacity for business continuity, refrigeration, tools, and home backup.',
    description: 'High-output backup power with expandable storage and smart monitoring.',
    price: 1190,
    old_price: 1390,
    image_url: deltaSeriesUrl,
    specs: { Capacity: '1.2kWh', Output: '1800W', 'Charge Time': '70 min', UPS: 'Yes' },
    badge: 'Sale',
    featured: true,
    active: true,
  },
  {
    id: 'solar-220',
    name: 'Eco Buka Solar Panel 220W',
    slug: 'eco-buka-solar-panel-220w',
    category_id: 'solar-panels',
    category: 'Solar Panels',
    short_description: 'Foldable solar panel with high conversion efficiency and weather-resistant finish.',
    description: 'Portable solar charging for stations, cabins, and field operations.',
    price: 319,
    image_url: solarPanelsUrl,
    specs: { Power: '220W', Cells: 'Monocrystalline', Rating: 'IP68', Weight: '7.2kg' },
    badge: 'New',
    featured: true,
    active: true,
  },
  {
    id: 'river-mini',
    name: 'Eco Buka River Mini',
    slug: 'eco-buka-river-mini',
    category_id: 'river-series',
    category: 'RIVER Series',
    short_description: 'Compact portable power for camping, travel, cameras, and daily backup.',
    description: 'A light mobile station made for quick charging and outdoor flexibility.',
    price: 249,
    old_price: 299,
    image_url: riverSeriesUrl,
    specs: { Capacity: '256Wh', Output: '300W', 'USB-C': '100W', Weight: '3.5kg' },
    badge: 'New',
    featured: true,
    active: true,
  },
  {
    id: 'solar-generator-kit',
    name: 'Eco Buka Solar Generator Kit',
    slug: 'eco-buka-solar-generator-kit',
    category_id: 'solar-generators',
    category: 'Solar Generators',
    short_description: 'Portable station and solar panel bundle for clean backup energy.',
    description: 'A ready-to-use solar generator kit for home backup and outdoor independence.',
    price: 899,
    old_price: 1049,
    image_url: streamSolarSystemUrl,
    specs: { Capacity: '1kWh', Panel: '220W', Output: '1200W' },
    badge: 'Bundle',
    featured: true,
    active: true,
  },
  {
    id: 'smart-monitor',
    name: 'Eco Buka Smart Energy Monitor',
    slug: 'eco-buka-smart-energy-monitor',
    category_id: 'smart-devices',
    category: 'Smart Devices',
    short_description: 'Monitor charging, backup status, and energy use from one smart device.',
    description: 'Connected energy monitoring for modern Eco Buka installations.',
    price: 129,
    image_url: smartDevicesUrl,
    specs: { App: 'Yes', Alerts: 'Real-time', Install: 'Easy' },
    badge: 'New',
    featured: false,
    active: true,
  },
  {
    id: 'accessory-cable-kit',
    name: 'Eco Buka Charging Accessory Kit',
    slug: 'eco-buka-charging-accessory-kit',
    category_id: 'accessories',
    category: 'Accessories',
    short_description: 'Essential adapters and charging cables for portable power setups.',
    description: 'A compact accessory kit for daily charging and field use.',
    price: 79,
    image_url: powerBanksUrl,
    specs: { Cables: '3', Adapters: '2', Case: 'Included' },
    badge: null,
    featured: false,
    active: true,
  },
  {
    id: 'home-backup-solution',
    name: 'Eco Buka Home Backup Solution',
    slug: 'eco-buka-home-backup-solution',
    category_id: 'solutions',
    category: 'Solutions',
    short_description: 'A complete package for backup power, solar charging, and daily resilience.',
    description: 'Designed for homes and businesses that need reliable energy continuity.',
    price: 1490,
    image_url: showcaseBannerUrl,
    specs: { Use: 'Home', Backup: 'Yes', Solar: 'Ready' },
    badge: 'Solution',
    featured: true,
    active: true,
  },
];

export const demoHomepageShowcase = {
  section: {
    id: 'homepage-showcase',
    section_key: 'solar_system_showcase',
    title: 'New Products',
    subtitle: 'Fresh energy solutions selected for homes, businesses, and outdoor power.',
    layout_type: 'products_with_navigation_and_banner',
    active: true,
    sort_order: 10,
  },
  productLinks: demoProducts.slice(0, 4).map((product, index) => ({
    id: `showcase-product-${product.id}`,
    section_id: 'homepage-showcase',
    product_id: product.id,
    product,
    active: true,
    sort_order: index + 1,
  })),
  navigationCards: [
    {
      id: 'showcase-nav-accessories',
      section_id: 'homepage-showcase',
      title: 'View All Accessories',
      link: '/category/accessories',
      image_url: powerBanksUrl,
      active: true,
      sort_order: 1,
    },
    {
      id: 'showcase-nav-solar',
      section_id: 'homepage-showcase',
      title: 'Explore Solar Kits',
      link: '/category/solar-panels',
      image_url: solarPanelsUrl,
      active: true,
      sort_order: 2,
    },
  ],
  banners: [
    {
      id: 'showcase-banner-delta',
      section_id: 'homepage-showcase',
      section_heading: 'Eco Buka DELTA Pro Ultra Power Station',
      eyebrow: 'New',
      title: 'Eco Buka DELTA Pro Ultra Power Station',
      subtitle: '6kWh-30kWh Capacity | 6900W Output',
      button_text: 'Buy Now',
      button_link: '/products/eco-buka-station-1200',
      background_image_url: showcaseBannerUrl,
      mobile_background_image_url: showcaseBannerUrl,
      text_color: 'light',
      text_alignment: 'left',
      active: true,
      sort_order: 1,
    },
  ],
};

export const demoPromotionalCategoryCards: HomepagePromoCard[] = [
  {
    id: 'promo-offers',
    section_key: 'promotional_category_cards',
    label: null,
    title: 'Promotional Offers',
    subtitle: 'Shop a great selection of deals, sale and clearance items.',
    button_text: 'Buy Now',
    button_link: '/products',
    category_slug: null,
    background_image_url: showcaseBannerUrl,
    mobile_background_image_url: showcaseBannerUrl,
    text_color: 'light',
    active: true,
    sort_order: 1,
  },
  {
    id: 'promo-home-battery',
    section_key: 'promotional_category_cards',
    label: null,
    title: 'Home Battery',
    subtitle: 'One powers all.',
    button_text: 'Contact Us',
    button_link: '/contact',
    category_slug: 'solutions',
    background_image_url: solarHomeUrl,
    mobile_background_image_url: solarHomeUrl,
    text_color: 'light',
    active: true,
    sort_order: 2,
  },
];

export const demoFeaturedVideoPromoBanners: HomepageBanner[] = [
  {
    id: 'featured-video-promo-default',
    section_id: 'featured-video-promo',
    section_heading: 'Eco Buka STREAM Series Plug & Play Solar Plant',
    eyebrow: 'FLASH SALE & Up to 43% OFF!',
    title: 'Eco Buka STREAM Series Plug & Play Solar Plant',
    subtitle: 'Run high-wattage appliances with clean solar power.',
    price_text: 'Starting at EUR 1199',
    button_text: 'Buy Now',
    button_link: '/category/solar-generators',
    background_video_url: null,
    background_image_url: solarHomeUrl,
    mobile_background_image_url: showcaseBannerUrl,
    text_color: 'light',
    text_alignment: 'left',
    active: true,
    sort_order: 1,
  },
];
