import type { Category } from '../types/category';
import type { HomepageBanner, HomepagePromoCard } from '../types/homepage';
import type { Product } from '../types/product';
import deltaSeriesUrl from '../assets/categories/delta-series.png';
import ocean2Url from '../assets/categories/ocean-2.png';
import powerBanksUrl from '../assets/categories/power-banks.png';
import refurbishedUrl from '../assets/categories/refurbished.png';
import riverSeriesUrl from '../assets/categories/river-series.png';
import smartDevicesUrl from '../assets/categories/smart-devices.png';
import solarPanelsUrl from '../assets/categories/solar-panels.png';
import streamSeriesUrl from '../assets/categories/stream-series.png';
import streamSolarSystemUrl from '../assets/categories/stream-solar-system.png';

const showcaseBannerUrl = '/promo/optimized/delta-max-series-1280.jpg';
const solarHomeUrl = '/promo/optimized/summer-sale-1280.jpg';

export const demoCategories: Category[] = [
  { id: 'power-stations', name: 'Stacione energjie', slug: 'power-stations', description: 'Stacione portative energjie për rezervë në shtëpi, përdorim në natyrë dhe vazhdimësi biznesi.', image_url: deltaSeriesUrl, is_new: false, active: true },
  { id: 'stream-series', name: 'Seria STREAM Plug & Play Solar Plant', slug: 'stream-series', description: 'Zgjidhje solare plug-and-play për prodhim të thjeshtë energjie në shtëpi.', image_url: streamSeriesUrl, is_new: true, active: true },
  { id: 'stream-solar-system', name: 'Sistemi solar STREAM Plug & Play', slug: 'stream-solar-system', description: 'Sisteme kompakte solare për kursim të përditshëm të energjisë në shtëpi.', image_url: streamSolarSystemUrl, is_new: true, active: true },
  { id: 'delta-series', name: 'Seria DELTA', slug: 'delta-series', description: 'Stacione portative me kapacitet të lartë për rezervë në shtëpi dhe energji profesionale.', image_url: deltaSeriesUrl, is_new: false, active: true },
  { id: 'river-series', name: 'Seria RIVER', slug: 'river-series', description: 'Energji e lehtë portative për natyrë, udhëtime dhe pajisje të përditshme.', image_url: riverSeriesUrl, is_new: true, active: true },
  { id: 'solar-panels', name: 'Panele solare', slug: 'solar-panels', description: 'Panele solare të palosshme dhe fikse për karikim të pastër kudo.', image_url: solarPanelsUrl, is_new: true, active: true },
  { id: 'solar-generators', name: 'Gjeneratorë solarë', slug: 'solar-generators', description: 'Sete gjeneratorësh solarë që kombinojnë karikimin e pastër me energji rezervë të besueshme.', image_url: streamSolarSystemUrl, is_new: false, active: true },
  { id: 'smart-devices', name: 'Pajisje inteligjente', slug: 'smart-devices', description: 'Pajisje të lidhura për monitorim dhe optimizim të energjisë në shtëpi.', image_url: smartDevicesUrl, is_new: true, active: true },
  { id: 'accessories', name: 'Aksesorë', slug: 'accessories', description: 'Kabllo karikimi, adaptorë, bateri dhe pajisje shtesë për sistemet Eco Buka.', image_url: powerBanksUrl, is_new: false, active: true },
  { id: 'solutions', name: 'Zgjidhje', slug: 'solutions', description: 'Zgjidhje të plota energjie për shtëpi, biznese, udhëtime dhe nevoja rezervë.', image_url: showcaseBannerUrl, is_new: false, active: true },
  { id: 'ocean-2', name: 'OCEAN 2', slug: 'ocean-2', description: 'Pajisje energjie për pishina, ambiente të jashtme dhe sisteme sezonale.', image_url: ocean2Url, is_new: false, active: true },
  { id: 'power-banks', name: 'Power bank', slug: 'power-banks', description: 'Karikim kompakt mobil për përdorim të përditshëm dhe rezervë në udhëtime.', image_url: powerBanksUrl, is_new: true, active: true },
  { id: 'refurbished', name: 'Të rinovuara', slug: 'refurbished', description: 'Produkte të kontrolluara profesionalisht për qasje më ekonomike në energji.', image_url: refurbishedUrl, is_new: false, active: true },
];

export const demoProducts: Product[] = [
  {
    id: 'eb-500',
    name: 'Eco Buka Station 500',
    slug: 'eco-buka-station-500',
    category_id: 'power-stations',
    category: 'Stacione energjie',
    short_description: 'Energji portative për telefona, laptopë, kamera, routerë dhe pajisje të vogla.',
    description: 'Stacion kompakt energjie për rezervë në shtëpi dhe përdorim në natyrë.',
    price: 499,
    old_price: 579,
    image_url: deltaSeriesUrl,
    specs: { Kapaciteti: '512Wh', Fuqia: '500W', 'Hyrja solare': '220W', Pesha: '6.4kg' },
    badge: 'Më i kërkuar',
    in_stock: true,
    featured: true,
    active: true,
  },
  {
    id: 'eb-1200',
    name: 'Eco Buka Station 1200',
    slug: 'eco-buka-station-1200',
    category_id: 'power-stations',
    category: 'Stacione energjie',
    short_description: 'Më shumë kapacitet për biznese, frigoriferë, vegla pune dhe rezervë në shtëpi.',
    description: 'Energji rezervë me fuqi të lartë, kapacitet të zgjerueshëm dhe monitorim inteligjent.',
    price: 1190,
    old_price: 1390,
    image_url: deltaSeriesUrl,
    specs: { Kapaciteti: '1.2kWh', Fuqia: '1800W', 'Koha e karikimit': '70 min', UPS: 'Po' },
    badge: 'Ofertë',
    in_stock: true,
    featured: true,
    active: true,
  },
  {
    id: 'solar-220',
    name: 'Eco Buka Solar Panel 220W',
    slug: 'eco-buka-solar-panel-220w',
    category_id: 'solar-panels',
    category: 'Panele solare',
    short_description: 'Panel solar i palosshëm me efikasitet të lartë dhe mbrojtje ndaj kushteve atmosferike.',
    description: 'Karikim solar portativ për stacione energjie, kabina dhe përdorim në terren.',
    price: 319,
    image_url: solarPanelsUrl,
    specs: { Fuqia: '220W', Qelizat: 'Monokristaline', Mbrojtja: 'IP68', Pesha: '7.2kg' },
    badge: 'E re',
    in_stock: true,
    featured: true,
    active: true,
  },
  {
    id: 'river-mini',
    name: 'Eco Buka River Mini',
    slug: 'eco-buka-river-mini',
    category_id: 'river-series',
    category: 'Seria RIVER',
    short_description: 'Energji kompakte portative për kamping, udhëtime, kamera dhe rezervë ditore.',
    description: 'Stacion i lehtë mobil për karikim të shpejtë dhe fleksibilitet në natyrë.',
    price: 249,
    old_price: 299,
    image_url: riverSeriesUrl,
    specs: { Kapaciteti: '256Wh', Fuqia: '300W', 'USB-C': '100W', Pesha: '3.5kg' },
    badge: 'E re',
    in_stock: true,
    featured: true,
    active: true,
  },
  {
    id: 'solar-generator-kit',
    name: 'Eco Buka Solar Generator Kit',
    slug: 'eco-buka-solar-generator-kit',
    category_id: 'solar-generators',
    category: 'Gjeneratorë solarë',
    short_description: 'Set me stacion portativ dhe panel solar për energji rezervë të pastër.',
    description: 'Set gjeneratori solar gati për përdorim në shtëpi dhe në natyrë.',
    price: 899,
    old_price: 1049,
    image_url: streamSolarSystemUrl,
    specs: { Kapaciteti: '1kWh', Paneli: '220W', Fuqia: '1200W' },
    badge: 'Set',
    in_stock: true,
    featured: true,
    active: true,
  },
  {
    id: 'smart-monitor',
    name: 'Eco Buka Smart Energy Monitor',
    slug: 'eco-buka-smart-energy-monitor',
    category_id: 'smart-devices',
    category: 'Pajisje inteligjente',
    short_description: 'Monitoroni karikimin, statusin e rezervës dhe përdorimin e energjisë nga një pajisje inteligjente.',
    description: 'Monitorim i lidhur i energjisë për instalime moderne Eco Buka.',
    price: 129,
    image_url: smartDevicesUrl,
    specs: { Aplikacioni: 'Po', Njoftimet: 'Në kohë reale', Instalimi: 'I thjeshtë' },
    badge: 'E re',
    in_stock: true,
    featured: false,
    active: true,
  },
  {
    id: 'accessory-cable-kit',
    name: 'Eco Buka Charging Accessory Kit',
    slug: 'eco-buka-charging-accessory-kit',
    category_id: 'accessories',
    category: 'Aksesorë',
    short_description: 'Adaptorë dhe kabllo karikimi të domosdoshme për sisteme portative energjie.',
    description: 'Set kompakt aksesorësh për karikim ditor dhe përdorim në terren.',
    price: 79,
    image_url: powerBanksUrl,
    specs: { Kabllo: '3', 'Adaptorë': '2', Kutia: 'E përfshirë' },
    badge: null,
    in_stock: true,
    featured: false,
    active: true,
  },
  {
    id: 'home-backup-solution',
    name: 'Eco Buka Home Backup Solution',
    slug: 'eco-buka-home-backup-solution',
    category_id: 'solutions',
    category: 'Zgjidhje',
    short_description: 'Paketë e plotë për energji rezervë, karikim solar dhe qëndrueshmëri të përditshme.',
    description: 'E krijuar për shtëpi dhe biznese që kanë nevojë për vazhdimësi të besueshme energjie.',
    price: 1490,
    image_url: showcaseBannerUrl,
    specs: { Përdorimi: 'Shtëpi', Rezervë: 'Po', Solar: 'Gati' },
    badge: 'Zgjidhje',
    in_stock: true,
    featured: true,
    active: true,
  },
];

export const demoHomepageShowcase = {
  section: {
    id: 'homepage-showcase',
    section_key: 'solar_system_showcase',
    title: 'Produktet e reja',
    subtitle: 'Zgjidhje të reja energjie të zgjedhura për shtëpi, biznese dhe përdorim në natyrë.',
    layout_type: 'products_with_navigation_and_banner',
    active: true,
    sort_order: 10,
  },
  productLinks: demoProducts.slice(0, 4).map((product, index) => ({
    id: `showcase-product-${product.id}`,
    section_id: 'homepage-showcase',
    product_id: product.id,
    product,
    active: true,
    sort_order: index + 1,
  })),
  navigationCards: [
    {
      id: 'showcase-nav-accessories',
      section_id: 'homepage-showcase',
      title: 'Shiko të gjithë aksesorët',
      link: '/category/accessories',
      image_url: powerBanksUrl,
      active: true,
      sort_order: 1,
    },
    {
      id: 'showcase-nav-solar',
      section_id: 'homepage-showcase',
      title: 'Shfleto setet solare',
      link: '/category/solar-panels',
      image_url: solarPanelsUrl,
      active: true,
      sort_order: 2,
    },
  ],
  banners: [
    {
      id: 'showcase-banner-delta',
      section_id: 'homepage-showcase',
      section_heading: 'Stacioni energjetik Eco Buka DELTA Pro Ultra',
      eyebrow: 'E re',
      title: 'Stacioni energjetik Eco Buka DELTA Pro Ultra',
      subtitle: 'Kapacitet 6kWh-30kWh | Fuqi 6900W',
      button_text: 'Bli tani',
      button_link: '/products/eco-buka-station-1200',
      background_image_url: showcaseBannerUrl,
      mobile_background_image_url: showcaseBannerUrl,
      text_color: 'light',
      text_alignment: 'left',
      active: true,
      sort_order: 1,
    },
  ],
};

export const demoPromotionalCategoryCards: HomepagePromoCard[] = [
  {
    id: 'promo-offers',
    section_key: 'promotional_category_cards',
    label: null,
    title: 'Oferta promovuese',
    subtitle: 'Shfletoni oferta, ulje dhe produkte të përzgjedhura.',
    button_text: 'Bli tani',
    button_link: '/products',
    category_slug: null,
    background_image_url: showcaseBannerUrl,
    mobile_background_image_url: showcaseBannerUrl,
    text_color: 'light',
    active: true,
    sort_order: 1,
  },
  {
    id: 'promo-home-battery',
    section_key: 'promotional_category_cards',
    label: null,
    title: 'Bateri për shtëpi',
    subtitle: 'Një zgjidhje që furnizon gjithçka.',
    button_text: 'Na kontaktoni',
    button_link: '/contact',
    category_slug: 'solutions',
    background_image_url: solarHomeUrl,
    mobile_background_image_url: solarHomeUrl,
    text_color: 'light',
    active: true,
    sort_order: 2,
  },
];

export const demoFeaturedVideoPromoBanners: HomepageBanner[] = [
  {
    id: 'featured-video-promo-default',
    section_id: 'featured-video-promo',
    section_heading: 'Eco Buka STREAM Series Plug & Play Solar Plant',
    eyebrow: 'Ofertë speciale dhe deri në 43% zbritje!',
    title: 'Eco Buka STREAM Series Plug & Play Solar Plant',
    subtitle: 'Furnizoni pajisje me konsum të lartë përmes energjisë së pastër solare.',
    price_text: 'Duke filluar nga 1199 EUR',
    button_text: 'Bli tani',
    button_link: '/category/solar-generators',
    background_video_url: null,
    background_image_url: solarHomeUrl,
    mobile_background_image_url: showcaseBannerUrl,
    text_color: 'light',
    text_alignment: 'left',
    active: true,
    sort_order: 1,
  },
];
